### ISSUE TITLE
Escape alternation (OR) | in markdown tables

### ISSUE THREAD

**Issue by GerMichael** [asyncapi/markdown-template#285]
#### Describe the bug

Using the regex alternation operator `|` in a pattern property of an AsyncAPI Schema Object disturbs the generated markdown table. The reason for that behaviour is the unescaped `|`. 

Used npm package versions:
 - `@asyncapi/generator: ^1.9.5`
 - `@asyncapi/markdown-template: ^1.1.1`

#### How to Reproduce

1. Create a new AsyncAPI file `sourcefile.yaml` and paste this definition:
    ```yaml
    asyncapi: "2.4.0"
    info:
      title: Streetlights MQTT API
      version: "1.0.0"
    
    servers:
      production:
        url: test.mosquitto.org:1883
        protocol: mqtt
    
    channels:
      smartylighting/streetlights/1/0/event/0/lighting/measured:
        publish:
          message:
            name: Arbitrary Message
            payload:
              type: string
              pattern: /foo|bar/
    ```

2. Generate the markdown file using the AsyncAPI generator and the `@asyncapi/markdown-template`-template, e.g., `ag sourcefile.yaml @asyncapi/markdown-template`

3. You should see in the "Operations" section the pattern displayed within two cells, split along the pipe operator
![image](https://user-images.githubusercontent.com/62344871/178255791-59a11707-5a1e-4f49-86be-09b9d0475f25.png)

#### Expected behavior

A pattern with an alternation operator should be displayed inside a single cell. Solution might be escaping `|` as described here: [https://www.designcise.com/web/tutorial/how-to-escape-the-pipe-character-in-a-markdown-table#escaping-the-pipe-character](https://www.designcise.com/web/tutorial/how-to-escape-the-pipe-character-in-a-markdown-table#escaping-the-pipe-character). 

Thanks!
