### ISSUE TITLE
Output contain valid XML tags

### ISSUE THREAD

**Issue by kjaquier** [asyncapi/markdown-template#365]
##### Context
I'm testing out templates for integrating an AsyncAPI spec into a [Docusaurus](https://docusaurus.io) website. Docusaurus uses MDX which allows integrating JSX components and code into Markdown documents. I assume it accepts XML tags as HTML/JSX components which other Markdown parsers might ignore and render as text.

##### Actual issue
The output contains elements like `array<integer>` that can look like unclosed HTML elements to some parsers.

#### How to Reproduce

Write an AsyncAPI schema that include a property like:
```yaml
type: object
properties:
  prop1:
    type: object
    properties:
      prop2:
        type: array
        items:
            type: number
``` 

The generated document will contain a table with this:
```
... | array<number> | ...
```

#### Expected behavior

The line above should be formatted as code:
```
... | `array<number>` | ...
```

There should be no `<` and `>` in the generated document that isn't formatted as code or escaped appropriately.
