### ISSUE TITLE
Support Slate markdown front-matter?

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/markdown-template#40]
#### Reason/Context

A suggestion to see if there is interest...

Adding the option (or creating a fork from this template) to add [Slate](https://github.com/slatedocs/slate) front-matter such as:

```yaml
---
title: Streetlights API 1.0.0 documentation
language_tabs: []
toc_footers: []
includes: []
search: true
code_clipboard: true
---
```

to the head of the generated markdown would allow immediate use of the output with Slate and compatible markdown renderers.

The output (with no changes to the template / ToC etc) looks like this:

https://mermade.github.io/shins/ag.html
