### ISSUE TITLE
AVRO Parsing Issue

### ISSUE THREAD

**Issue by viren1123** [asyncapi/markdown-template#94]
I'm getting the following error if I use AVRO schema in the AsynAPI document and try to generate a markdown document using generator:

Something went wrong:
```bash
TypeError: prop.anyOf is not a function
    at SchemaProp (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\markdown-template\components\Schema.js:23:22)
    at createElement (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:46:26)
    at C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:69:26)
    at C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:71:14
    at Array.map (<anonymous>)
    at render (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:69:26)
    at createElement (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:34:12)
    at createElement (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:46:12)
    at C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:70:26
    at Array.map (<anonymous>)
    at render (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:69:26)
    at C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:71:14
    at Array.map (<anonymous>)
    at render (C:\Users\virender_kumar\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\renderer.ts:69:26)
```

**AsyncAPI schema:**

```yaml
asyncapi: '2.0.0'
info:
  title: Test API
  version: '1.0.0'
  description: |
    The Test API 
  license:
    name: <license_name>
    url: 'https://<license_url>'

servers:
  message_broker:
    url: http://<broker_url>
    description: Kafka message broker
    protocol: kafka

channels:
  kafka-job:
    description: Kafka topic
    subscribe:
      summary: Consumer.
      operationId: process_job
      message:
        name: PreprocessedJob
        schemaFormat: 'application/vnd.apache.avro+yaml;version=1.9.0'
        payload:
          $ref: D:/avro_schema/job.avsc
```

**AVRO File:**

```js
{
    "namespace": "com.schema",
    "type": "record",
    "name": "PreprocessedJob",
    "fields": [
       { "name": "fileLocation", "type": ["null", "string"],"default": null },
       { "name": "fileName", "type": ["null", "string"],"default": null},
       { "name": "id", "type": ["null", "string"],"default": null },
       { "name": "code", "type": ["null", "string"],"default": null },
       { "name": "company", "type": ["null", "string"],"default": null },
       { "name": "source", "type": ["null", "string"],"default": null },
       { "name": "skills", "type": ["null", {"type": "map", "values": "int"}],"default": null }
    ]
 }
```
